# Generated by Django 3.2.5 on 2024-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=50)),
                ('subscriber', models.CharField(max_length=50)),
            ],
        ),
    ]
